name: Streak

on:
  schedule:
    - cron: '20 14 * * *'  # 19:50 IST daily
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    # If using environment secret, uncomment:
    # environment: infra

    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ secrets.USER_EMAIL }}"

      - name: Make empty commit
        run: |
          git commit --allow-empty -m "Streak grass: $(date +'%Y-%m-%d %H:%M:%S')"

      - name: Push commit
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git push https://${GH_PAT}@github.com/${{ github.repository }} HEAD:main
