name: Streak

on:
  schedule:
    - cron: '20 14 * * *'  # 19:50 IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ secrets.USER_EMAIL }}"

      - name: Make empty commit
        run: |
          git commit --allow-empty -m "Streak grass: $(date +'%Y-%m-%d %H:%M:%S')"

      - name: Push commit
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:main
